### ISSUE TITLE
channel server issue!

### ISSUE THREAD

**Issue by IDontHaveBrain** [retep998/Vana#6]
Worldserver send ping packet (11 00) to channelserver.

Channelserver handle ping packet to return Result::Failure;
So Channelserver always say 'disconnected form worldserver' when recv ping packet.

My temp fix - 
world_server_session.cpp
delete line53.

Sry, my poor english.
- What is vedb ? instead of mcdb ?
- Where can I get svn repo link ?

**Comment by LazyBui** [comment]
Thanks for the report. The issue you describe should be fixed in https://github.com/retep998/Vana/commit/03131e0d35c25a731f543b36b70d9b623fcdbfec.

VEDB stands for Vana Enhanced Database. It's the same project as MCDB, it was renamed. VEDB shouldn't be useful to anybody but historians at this point.

The SVN repo is no longer up even for developers. So this github repository is the closest thing you'll get to it.

Closing.
